name: Create Cores DB

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '*/20 * * * *'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Create Cores DB
      run: ./.github/create_cores_db.sh
